version: "3"
services:
  hugo-build:
    image: klakegg/hugo:0.81.0-ext-alpine
    volumes:
      - .:/src
      - ./public:/target

  hugo-shell:
    image: klakegg/hugo:0.81.0-ext-alpine
    command: shell
    volumes:
      - .:/src

  hugo-server:
    image: klakegg/hugo:0.81.0-ext-alpine
    command: server -D
    volumes:
      - .:/src
    ports:
      - 1313:1313
