version: "3"
services:

  build:
    build: .
    environment:
      - DEBUG=*
    volumes:
      - .:/app

  server:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: --serve
    ports:
      - "8080:8080"
