on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.2.0
      - run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          publish_branch: master
          publish_dir: ./public
          cname: gtramontina.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
